export enum ApiRouteEnum {
  LOGIN = '/auth/token',
  GET_PROFILE = '/auth/me',
  LOGOUT = '/auth/logout',
  LIST_SIZES = '/products-csc/size/list',
  UPDATE_SIZE = '/products-csc/size',
  SIZES = '/products-csc/size',
  LIST_COLORS = '/products-csc/color/list',
  UPDATE_COLOR = '/products-csc/color',
  COLORS = '/products-csc/color',
  CREATE_PRODUCT = '/products-csc/create',
  DELETE_PRODUCT = '/products-csc/delete',
  UPDATE_PRODUCT_THUMBNAIL = '/products/thumbnail/update',
  UPDATE_PRODUCT_IMAGES = '/products/images/update',
  LIST_PRODUCTS = '/products/list',
  CATEGORIES = '/products-csc/category/list',
}
