export const AppRouteEnums = {
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  CHECKOUT_CART: '/checkout/cart',
  CHECKOUT_PAYMENT: '/checkout/payment',
  CHECKOUT_ORDER: '/checkout/order',
  HOME: '/',
  USER: '/user',
  USER_EDIT_PROFILE: '/user/edit-profile',
  USER_DELIVERY_ADDRESS: '/user/delivery-address',
  USER_ORER_HISTORY: '/user/order-history',
  USER_UPDATE_PASSWORD: '/user/update-password',
  CONTACT: '/contact',
  BLOGS: '/blogs',
};
